//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTechnicalHiring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessage
    {
        public int MID { get; set; }
        public Nullable<int> MsgFromId { get; set; }
        public Nullable<int> MsgToId { get; set; }
        public string Msg { get; set; }
    }
}
