//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTechnicalHiring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int RID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> UID { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual tblTechnician tblTechnician { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
